name: es-keras
channels:
- kne
- defaults
dependencies:
- openssl=1.0.2k=1
- pip=9.0.1=py35_1
- python=3.5.3=1
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pybox2d=2.3.1post2=py35_0
- pip:
  - box2d==2.3.1
  - gym==0.8.1
  - numpy==1.12.1
  - pyglet==1.2.4
  - requests==2.13.0
  - six==1.10.0

